# Hyper
model: SASRec
dataset: beauty
tool: Ray

# Model Settings
embedding_size: 50
attn_dropout_prob: 0.2
hidden_dropout_prob: 0.2

# Data Settins
MAX_ITEM_LIST_LENGTH: 50
load_col:
  inter: [user_id, item_id, timestamp]

# Training Settings
learning_rate: 0.001
train_batch_size: 128
train_neg_sample_args: ~

# Evalution Settings
topk: [10, 20]
eval_batch_size: 128
eval_args:
  { "split": { "LS": "valid_and_test" }, "order": "TO", "mode": "uni100" }
